import type { Metadata } from "next";
import "./globals.css";
import TRPCProvider from "./_trpc/TRPCProvider";
import { twMerge } from "tailwind-merge";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={twMerge(GeistSans.className, "h-screen w-screen")}>
        <TRPCProvider>
          <div className="w-full h-full">{children}</div>
        </TRPCProvider>
        <Toaster />
      </body>
    </html>
  );
};
export default RootLayout;
