import type { Metadata } from "next";
import "./globals.css";
import TRPCProvider from "./_trpc/TRPCProvider";
import { twMerge } from "tailwind-merge";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/components/wrapper/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={twMerge(GeistSans.className, "h-screen w-screen")}>
        <SessionProvider session={session}>
          <TRPCProvider>
            <div className="w-full h-full">{children}</div>
          </TRPCProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
};
export default RootLayout;
