import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TRPCProvider from "./_trpc/TRPCProvider";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, "h-screen w-screen")}>
        <TRPCProvider>
          <div className="w-full h-full">{children}</div>
        </TRPCProvider>
      </body>
    </html>
  );
};
export default RootLayout;
